PermsManager/Controllers/PrEntryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PermsManager.Models;

namespace PermsManager.Controllers
{ 
    public class PrEntryController : Controller
    {
        private McPermissonsEntities db = new McPermissonsEntities();

        //
        // GET: /PrEntry/

        public ViewResult Index()
        {
            var prentries = db.PrEntries.Include("PrWorld");
            return View(prentries.ToList());
        }

        //
        // GET: /PrEntry/Details/5

        public ViewResult Details(int id)
        {
            PrEntry prentry = db.PrEntries.Single(p => p.entryid == id);
            if (prentry.type.Equals(1))
            {
                ViewBag.groups = prentry.Children.Where(p => p.Child.type.Equals(1));
                ViewBag.users = prentry.Children.Where(p => p.Child.type.Equals(0));
                ViewBag.permissions = prentry.PrPermissions.Where(p => p.entryid.Equals(id));
            }
            else
            {
                ViewBag.groups = prentry.Parents.Where(p => p.Parent.type.Equals(1));
                ViewBag.users = prentry.Parents.Where(p => p.Parent.type.Equals(0));
                ViewBag.permissions = prentry.PrPermissions.Where(p => p.entryid.Equals(id));
            }
            return View(prentry);
        }

        //
        // GET: /PrEntry/Create

        public ActionResult Create()
        {
            ViewBag.worldid = new SelectList(db.PrWorlds, "worldid", "worldname");
            return View();
        } 

        //
        // POST: /PrEntry/Create

        [HttpPost]
        public ActionResult Create(PrEntry prentry)
        {
            if (ModelState.IsValid)
            {
                db.PrEntries.AddObject(prentry);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.worldid = new SelectList(db.PrWorlds, "worldid", "worldname", prentry.worldid);
            return View(prentry);
        }
        
        //
        // GET: /PrEntry/Edit/5
 
        public ActionResult Edit(int id)
        {
            PrEntry prentry = db.PrEntries.Single(p => p.entryid == id);
            ViewBag.worldid = new SelectList(db.PrWorlds, "worldid", "worldname", prentry.worldid);
            return View(prentry);
        }

        //
        // POST: /PrEntry/Edit/5

        [HttpPost]
        public ActionResult Edit(PrEntry prentry)
        {
            if (ModelState.IsValid)
            {
                db.PrEntries.Attach(prentry);
                db.ObjectStateManager.ChangeObjectState(prentry, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = prentry.entryid });
            }
            ViewBag.worldid = new SelectList(db.PrWorlds, "worldid", "worldname", prentry.worldid);
            return View(prentry);
        }

        //
        // GET: /PrEntry/Delete/5
 
        public ActionResult Delete(int id)
        {
            PrEntry prentry = db.PrEntries.Single(p => p.entryid == id);
            return View(prentry);
        }

        //
        // POST: /PrEntry/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            PrEntry prentry = db.PrEntries.Single(p => p.entryid == id);
            db.PrEntries.DeleteObject(prentry);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PermsManager/Controllers/PrPermissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PermsManager.Models;

namespace PermsManager.Controllers
{
    public class PrPermissionsController : Controller
    {
        private McPermissonsEntities db = new McPermissonsEntities();

        //
        // GET: /PrPermissions/

        public ViewResult Index()
        {
            var prpermissions = db.PrPermissions.Include("PrEntry");
            return View(prpermissions.ToList());
        }

        //
        // GET: /PrPermissions/Details/5

        public ViewResult Details(int id)
        {
            PrPermission prpermission = db.PrPermissions.Single(p => p.permid == id);
            return View(prpermission);
        }

        //
        // GET: /PrPermissions/Create

        public ActionResult Create(int id = -1)
        {
            if (id == -1)
            {
                ViewBag.entryid = new SelectList(db.PrEntries, "entryid", "name");
                ViewBag.prentry = null;
            }
            else
            {
                ViewBag.prentry = db.PrEntries.Single(p => p.entryid == id);
            }
            return View();
        }

        //
        // POST: /PrPermissions/Create

        [HttpPost]
        public ActionResult Create(PrPermission prpermission)
        {
            ViewBag.prentry = null;
            if (ModelState.IsValid)
            {
                db.PrPermissions.AddObject(prpermission);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.entryid = new SelectList(db.PrEntries, "entryid", "name", prpermission.entryid);
            return View(prpermission);
        }

        //
        // GET: /PrPermissions/Edit/5

        public ActionResult Edit(int id)
        {
            PrPermission prpermission = db.PrPermissions.Single(p => p.permid == id);
            ViewBag.entryid = new SelectList(db.PrEntries, "entryid", "name", prpermission.entryid);
            return View(prpermission);
        }

        //
        // POST: /PrPermissions/Edit/5

        [HttpPost]
        public ActionResult Edit(PrPermission prpermission)
        {
            if (ModelState.IsValid)
            {
                db.PrPermissions.Attach(prpermission);
                db.ObjectStateManager.ChangeObjectState(prpermission, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.entryid = new SelectList(db.PrEntries, "entryid", "name", prpermission.entryid);
            return View(prpermission);
        }

        //
        // GET: /PrPermissions/Delete/5

        public ActionResult Delete(int id)
        {
            PrPermission prpermission = db.PrPermissions.Single(p => p.permid == id);
            return View(prpermission);
        }

        //
        // POST: /PrPermissions/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            PrPermission prpermission = db.PrPermissions.Single(p => p.permid == id);
            db.PrPermissions.DeleteObject(prpermission);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PermsManager/Views/PrEntry/Create.cshtml
@model PermsManager.Models.PrEntry

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>User or Group</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.name)
            @Html.ValidationMessageFor(model => model.name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.worldid, "PrWorld")
        </div>
        <div class="editor-field">
            @Html.DropDownList("worldid", String.Empty)
            @Html.ValidationMessageFor(model => model.worldid)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.type)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.type)
            @Html.ValidationMessageFor(model => model.type)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    <a href="javascript: history.go(-1)">Back</a>
</div>

PermsManager/Views/PrEntry/Delete.cshtml
@model PermsManager.Models.PrEntry

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>>@Model.name</legend>

    <div class="display-label">name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.name)
    </div>

    <div class="display-label">PrWorld</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PrWorld.worldname)
    </div>

    <div class="display-label">type</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.type)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

<div>
    <a href="javascript: history.go(-1)">Back</a>
</div>

PermsManager/Views/PrEntry/Details.cshtml
@model PermsManager.Models.PrEntry
@using PermsManager.Models
@{
    ViewBag.Title = "Details";
    
}
<h2>
    Details</h2>
<fieldset>
    <legend>@Model.name</legend>
    <div class="display-label">
        World: @Html.DisplayFor(model => model.PrWorld.worldname)</div>
    <div>
        <table width="10%">
            <thead>
                <tr>
                    <th style="text-align:left">
                        <h2>
                            Groups</h2>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (PrInheritance group in ViewBag.groups)
                {
                    <tr>
                        <td>
                            @if (Model.type.Equals(0))
                            {
                                <a href="../../PrEntry/Details/@group.Parent.entryid">@group.Parent.name</a>
                            }
                            else
                            {
                                <a href="../../PrEntry/Details/@group.Child.entryid">@group.Child.name</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div>
        <table width="10%">
            <thead>
                <tr>
                    <th style="text-align:left">
                        <h2>
                            Users</h2>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (PrInheritance user in ViewBag.users)
                {
                    <tr>
                        <td>
                            <a href="../../PrEntry/Details/@user.Child.entryid">@user.Child.name</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
        <div>
        <table width="10%">
            <thead>
                <tr>
                    <th style="text-align:left">
                        <h2>
                            Permissions</h2>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                <td>
                @Html.ActionLink("Create New", "Create", "PrPermissions", new { id = Model.entryid }, null);
                </td>
                </tr>
                @foreach (PrPermission perm in ViewBag.permissions)
                {
                    <tr>
                        <td>
                            @perm.permstring
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.entryid }) | <a href="javascript: history.go(-1)">
        Back</a>
</p>

PermsManager/Views/PrEntry/Edit.cshtml
@model PermsManager.Models.PrEntry

@{
    ViewBag.Title = Model.name;
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>@Model.name</legend>

        @Html.HiddenFor(model => model.entryid)

        <div class="editor-label">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.name)
            @Html.ValidationMessageFor(model => model.name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.worldid, "PrWorld")
        </div>
        <div class="editor-field">
            @Html.DropDownList("worldid", String.Empty)
            @Html.ValidationMessageFor(model => model.worldid)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.type)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.type)
            @Html.ValidationMessageFor(model => model.type)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    <a href="javascript: history.go(-1)">Back</a>
</div>

PermsManager/Views/PrEntry/Index.cshtml
@model IEnumerable<PermsManager.Models.PrEntry>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            name
        </th>
        <th>
            PrWorld
        </th>
        <th>
            type
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PrWorld.worldname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.type)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.entryid }) |
            @Html.ActionLink("Details", "Details", new { id=item.entryid }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.entryid })
        </td>
    </tr>
}

</table>

<div>
    <a href="javascript: history.go(-1)">Back</a>
</div>